notifications:
  email:
    on_success: never

branches:
  only:
  - master

language: minimal

env:
  - DOCKER_COMPOSE_VERSION=1.23.0

services:
  - docker

before_install:
    - sudo rm /usr/local/bin/docker-compose
    - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
    - chmod +x docker-compose
    - sudo mv docker-compose /usr/local/bin
    - mkdir -p docker-images
    - test -e docker-images/php.tar.gz && gzip -dc docker-images/php.tar.gz | docker load
script:
    - bash docker/start.sh
    - docker save php | gzip > docker-images/php.tar.gz
    - docker exec -ti php /bin/bash -c 'bash update.sh'
