version: '3'
services:
    php:
        container_name: php
        build: ./docker/php
        image: phpquiz-php
        entrypoint: /var/www/docker/php/entrypoint.sh
        volumes:
            - .:/var/www
    database:
        container_name: database
        image: mariadb
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - /var/lib/mysql:/var/lib/mysql
