version: '3'
services:
    php:
        container_name: phpquiz
        build: ./docker/php
        image: my-php
        restart: always
        entrypoint: /var/www/docker/php/entrypoint.sh
        volumes:
            - .:/var/www
    database:
        container_name: phpquiz-database
        image: mariadb
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - /var/lib/mysql:/var/lib/mysql
