version: '3'
services:
  php:
    container_name: php
    build: ./docker/php
    volumes:
      - ./cron/phpquiz-crontab:/etc/cron.d/phpquiz-crontab
      - .:/var/www
  mailcatcher:
    container_name: mailcatcher
    image: schickling/mailcatcher
    ports:
      - "1080:1080"