#!/usr/bin/env bash
echo -e "\e[32m> Starting pre-commit hook ...\e[0m"

PHP_CS_FIXER="vendor/bin/php-cs-fixer"
PHP_CS_CONFIG=".php_cs"
CHANGED_FILES=$(git diff --cached --name-only --diff-filter=ACM -- '*.php')

if [[ -n "$CHANGED_FILES" ]]; then
    echo -e "\e[32m> Running php-cs-fixer ...\e[0m"
    sudo docker exec -e PHP_CS_FIXER_IGNORE_ENV=1 php ${PHP_CS_FIXER} fix --config "$PHP_CS_CONFIG" ${CHANGED_FILES};
    git add ${CHANGED_FILES};
fi

echo -e "\e[32m> Stopping pre-commit hook ...\e[0m"
