#!/usr/bin/env bash
echo "php-cs-fixer pre commit hook start"

PHP_CS_FIXER="vendor/bin/php-cs-fixer"
CHANGED_FILES=$(git diff --cached --name-only --diff-filter=ACM -- '*.php')

if [ -n "$CHANGED_FILES" ]; then
    $PHP_CS_FIXER fix $CHANGED_FILES --rules=@PSR1,@PSR2,@Symfony,@Symfony:risky --allow-risky=yes;
    git add $CHANGED_FILES;
fi

echo "php-cs-fixer pre commit hook finish"